# Generated by Django 6.0.4 on 2026-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.CharField(max_length=200)),
                ('duree', models.IntegerField(help_text='Durée en jours')),
                ('prix', models.FloatField()),
                ('capacite_max', models.IntegerField()),
                ('places_disponibles', models.IntegerField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='circuits/')),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['-date_creation'],
            },
        ),
    ]
